# AWS Lambda Privilege Escalation Investigation

## Scenario

A suspicious privilege escalation has been detected involving an AWS Lambda function. The goal is to identify which IAM identity was ultimately targeted after the attacker abused the Lambda execution role.

The investigation is performed using CloudTrail logs inside Kibana.

---

# Investigation Process

## Step 1 — Focus on CloudTrail Logs

First, limit the investigation to AWS CloudTrail events.

```kql
event.dataset:"aws.cloudtrail"
```

This removes unrelated logs and keeps only AWS API activity.

---

## Step 2 — Find Suspicious Lambda Invocations

Search for Lambda Invoke events.

```kql
event.dataset:"aws.cloudtrail"
and event.provider:"lambda.amazonaws.com"
and event.action:"Invoke"
```

### Why?

Privilege escalation starts with a Lambda execution.

The goal here is to identify:

- Which Lambda function was executed
- When it was executed
- Which IP or user invoked it

In this challenge the suspicious function is:

```
Bucket-mgmgt-Functionbuk
```

---

## Step 3 — Pivot to the Lambda Execution Role

Now investigate everything performed by the Lambda execution role.

```kql
event.dataset:"aws.cloudtrail"
and user.name:"LambdaExecutionRole"
```

or narrow it further

```kql
event.dataset:"aws.cloudtrail"
and user.name:"LambdaExecutionRole"
and aws.cloudtrail.request_parameters:*Bucket-mgmgt-Functionbuk*
```

### Why?

Every action executed by the Lambda function is performed under its execution role.

This shows what permissions the function actually used.

Typical events include:

- KMS Decrypt
- IAM APIs
- STS APIs
- S3 APIs

---

## Step 4 — Check for AssumeRole

Privilege escalation commonly occurs when one role assumes another.

Search for AssumeRole events.

```kql
event.dataset:"aws.cloudtrail"
and event.action:"AssumeRole"
```

To isolate Lambda-originated AssumeRole calls:

```kql
event.dataset:"aws.cloudtrail"
and event.action:"AssumeRole"
and user_agent.original:"lambda.amazonaws.com"
```

### Why?

If the Lambda assumes another IAM role, it may inherit permissions that were never intended for the function.

In this challenge the Lambda assumes:

```
arn:aws:iam::851725491209:role/LambdaExecutionRole
```

This confirms the function is executing with temporary STS credentials.

---

## Step 5 — Look for GetSessionToken

Once temporary credentials are involved, search for STS session creation.

```kql
event.dataset:"aws.cloudtrail"
and event.action:"GetSessionToken"
```

### Why?

Temporary credentials generated by STS are linked to the IAM identity that requested them.

This event reveals the identity that ultimately becomes associated with the privileged session.

Unlike the AssumeRole event—which only shows that the Lambda obtained temporary credentials—the GetSessionToken event exposes the targeted IAM identity.

---

## Step 6 — Identify the Targeted Identity

Inspect the GetSessionToken event.

The required answer is:

```
userIdentity.arn
```

This ARN represents the IAM identity associated with the privileged session.

---

# Investigation Flow

```
Lambda Invoke
        │
        ▼
Bucket-mgmgt-Functionbuk
        │
        ▼
LambdaExecutionRole
        │
        ▼
AssumeRole
        │
        ▼
GetSessionToken
        │
        ▼
Target userIdentity.arn
```

---

# Investigation Mindset

Instead of searching randomly, each query should answer one specific question.

| Question | Query |
|----------|-------|
| Was a Lambda invoked? | `event.action:"Invoke"` |
| Which function? | Inspect Invoke event |
| What role executed it? | `user.name:"LambdaExecutionRole"` |
| Did it assume another role? | `event.action:"AssumeRole"` |
| Were temporary credentials issued? | `event.action:"GetSessionToken"` |
| Which identity became associated with them? | Inspect `userIdentity.arn` |

Each answer should naturally lead to the next question.

---

# Key Takeaways

- Lambda functions execute using an IAM execution role.
- Temporary credentials are obtained through STS.
- `AssumeRole` shows that a role was assumed.
- `GetSessionToken` helps correlate the resulting temporary session with the associated IAM identity.
- Successful cloud investigations rely on correlation rather than isolated events.
